# Generated by Django 4.0.3 on 2022-03-20 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'Не ищу работу'), ('1', 'Рассматриваю предложения'), ('2', 'Ищу работу')], max_length=25)),
                ('salary', models.IntegerField()),
                ('specialty', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('0', 'Стажер'), ('1', 'Джуниор'), ('2', 'Миддл'), ('3', 'Синьор'), ('4', 'Лид')], max_length=25)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
